Implementation of MK docs.
FAIRmat-NFDI/nyaml pull request #33
Opened 2024-04-29 14:02 UTC by RubelMozumder

2024-06-03 07:29 UTC, lukaspie commented on pyproject.toml
> +    "mkdocs-mermaid2-plugin"
```suggestion
    "mkdocs-mermaid2-plugin",
```

2025-02-05 15:45 UTC, lukaspie requested changes
Initial round of review, there are many places that could be improved. Would also be nice to improve the style a bit to be closer to the style of the documentation of our other tools.

2025-02-05 15:45 UTC, lukaspie commented on docs/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
```suggestion
The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those engaged in neutron, X-ray, and muon research [J. Appl. Cryst. (2015). 48, 301-305](https://doi.org/10.1107/S1600576714027575). The data format is also being used by the material science community under the project [NeXus-FAIRmat](https://fairmat-nfdi.github.io/nexus_definitions/) supporting FAIR (Findable, Accessible, Interoperable and Reuseable) data principles. It serves as a standardized framework for both data exchange and storage. At its core, the NeXus Definition Language (NXDL) functions as the cornerstone through which scientists delineate the nomenclature and organizational structure of information within NeXus data files, tailored to specific scientific techniques.
```

2025-02-05 15:45 UTC, lukaspie commented on docs/explanations.md
> +The `YAML` format, while not yet an official version of NeXus application definitions or base classes, necessitates a method for transcoding it into `XML`. The [nyaml](https://github.com/FAIRmat-NFDI
```suggestion
The `YAML` format, while not yet an official version of NeXus application definitions or base classes, necessitates a method for transcoding it into `XML`. The [nyaml](https://github.com/FAIRmat-NFDI/nyaml/tree/main) Python package serves as a converter tool designed specifically for this purpose. It enables the conversion of NXDL from `YAML` format to `XML`, thereby enhancing the capability of NeXus schema developers to incorporate domain-specific scientific knowledge into the schema. Furthermore, the tool offers the flexibility to extend existing NeXus schemas in XML by facilitating conversion back and forth between the two formats. It is important to note that here we do not introduce NeXus data objects, terms, or types, which are fundamental for writing base class schemas or application definition schemas. For individuals new to NeXus, we refer to the [official NeXus site](https://www.nexusformat.org/).
```

2025-02-05 15:45 UTC, lukaspie commented on docs/index.md
> +- [Tutorials to write NeXus definition in YAML](tutorials.md)
```suggestion
- [Tutorials for writing NeXus definition in YAML](tutorials.md)
```

2025-02-05 15:45 UTC, lukaspie commented on docs/index.md
> +- [Motivation for NYAML tool](explanations.md)
```suggestion
- [Explanation of the nyaml tool](explanations.md)
```

2025-02-05 15:45 UTC, lukaspie commented on docs/index.md
> +</div>
```suggestion
### References

- [NYAML GitHub repository](https://github.com/FAIRmat-NFDI/nyaml)
- [FAIRmat-NeXus website](https://fairmat-experimental.github.io/nexus-fairmat-proposal/)
- [FAIRmat-NeXus GitHub repository](https://github.com/FAIRmat-NFDI/nexus_definitions)
- [Official NeXus website](https://manual.nexusformat.org/index.html)
</div>
</div>

<h2>Project and community</h2>

Any questions or suggestions? [Get in touch!](https://www.fair-di.eu/fairmat/about-fairmat/team-fairmat)

[The work is funded by the Deutsche Forschungsgemeinschaft (DFG, German Research Foundation) - 460197019 (FAIRmat).](https://gepris.dfg.de/gepris/projekt/460197019?language=en)
```

2025-02-05 15:45 UTC, lukaspie commented on tests/data/dimensions_parsed.yaml
> +category: application
These changes seem unconnected from the rest of the PR, is this a rebase issue?

2025-02-05 15:45 UTC, lukaspie commented on docs/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
I think most of this should actually go to the `index.md` file as an introduction to the tool.

2025-02-05 15:45 UTC, lukaspie commented on docs/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
Basically, everything in this paragraph should just go to the index file.

2025-02-05 15:45 UTC, lukaspie commented on docs/how_to_guide.md
> +The `nyaml` is pathon package [published in PyPI](https://pypi.org/project/nyaml/) therefore easy to use and install.
```suggestion
`nyaml` is a Python package [published on PyPI](https://pypi.org/project/nyaml/).
```

2025-02-05 15:45 UTC, lukaspie commented on docs/how_to_guide.md
> +To contribute to the tool or to install it in development mode
```suggestion
To contribute to the tool or to install it in development mode, you should run
```

2025-02-05 15:45 UTC, lukaspie commented on docs/how_to_guide.md
> +The `nyaml` works as a command line tool to convert NeXus application definition or base class from `yaml` file format into the `nxdl.xml` file format and vice-versa. The converter can be called by t
```suggestion
`nyaml` works as a command line tool to convert NeXus application definitions or base classes from `yaml` file format into the `nxdl.xml` file format and vice-versa. The converter can be called by the command
```

2025-02-05 15:45 UTC, lukaspie commented on pyproject.toml
> +
add mkdocs-click, see comment in docs/how_to_guide.md

2025-02-05 15:45 UTC, lukaspie commented on mkdocs.yml
> +  - md_in_html
add mkdocs-click

2025-02-05 15:45 UTC, lukaspie commented on docs/how_to_guide.md
> +```bash
Use [`mkdocs-click`](https://github.com/mkdocs/) in the pyproject.toml file and then here, we can do
```
::: mkdocs-click
    :module: nyaml.cli
    :command: launch_tool
    :prog_name: nyaml2nxdl
    :depth: 2
    :style: table
    :list_subcommands: True
```

2025-02-05 15:45 UTC, lukaspie commented on mkdocs.yml
> +  - Reference: references.md
this file does not exist

2025-02-05 15:45 UTC, lukaspie commented on docs/how_to_guide.md
> +The `--output-file` option can be used to define the output file name (including the fle extension), otherwise the converter will define the output file name from the input file, e.g., for the input
```suggestion

- The `--output-file` option can be used to define the output file name (including the file extension), otherwise the converter will define the output file name from the input file, e.g., for the input file `NXapplication.nxdl.xml (NXapplication.yaml)`, the resultant file will be `NXapplication_parsed.yaml (NXapplication.nxdl.xml)`. 
- With the option `--check-consistency` the converter produces the same type of file as the input, e.g. for input `NXapplication.nxdl.xml`, the output file is `NXapplication_consistency.nxd.xml`. The intention for this option is to verify proper file and version conversion of the file. 
- When converting the `nxdl.xml` file into `yaml` it also stores the `nxdl.xml` file at the end of `yaml` file with a hash. The option `--do-not-store-nxdl` prevents the `yaml` file from storing the original `nxdl.xml` text. 
- The `verbose` option is to identify any issues arising from unexpected conversion or syntax errors that occur while converting the file from one to another.
```

What do you mean by "proper file and version conversion"?

2025-02-05 15:45 UTC, lukaspie commented on docs/how_to_guide.md
> +The `--output-file` option if user wants to define output file name (including extension) otherwise converter will define the output file name e.g. from input file `NXapplication.nxdl.xml (NXapplicat
this seems to be duplicated, remove

2025-02-05 15:45 UTC, lukaspie commented on docs/tutorials.md
> +This tutorial will explain different keywords, terms and rules from the prespective of YAML format of the NeXus schema.
```suggestion
This tutorial will explain different keywords, terms, and rules from the perspective of YAML format of the NeXus schema.
```

Honestly, this is not a tutorial. It should rather go to explanations.

2025-02-05 15:45 UTC, lukaspie commented on docs/tutorials.md
> +Furthermore, the uppercase part of the group's name can be dynamically overwritten, allowing for the instantiation of multiple instances. For example, `source_electric` and `source_magnetic` can coex
This is now covered by `nameType=partial`, the documentation here should be updated.

2025-02-05 15:45 UTC, lukaspie commented on docs/tutorials.md
> +**NeXus choice in YAML format**
This doesn't work yet, see https://github.com/FAIRmat-NFDI/nyaml/issues/23.

So, I don't think we should mention it here yet.

2025-02-05 15:45 UTC, lukaspie commented on docs/tutorials.md
> +In the example the valid value for NeXus field `definition` is `NXmpes`.
```suggestion
In the example, the only valid value for NeXus field `definition` is `NXmpes`.
```

2025-02-05 15:45 UTC, lukaspie commented on docs/tutorials.md
> +The `xref` keyword (which can only inside the keyword `doc`) is used to refer any other ontology or any other standard such `ISO`. The `xref` in the example `doc` will reflect the information inside
```suggestion
The `xref` keyword (which can only be used inside the keyword `doc`) is used to refer any other ontology or any other standard such `ISO`. The `xref` in the example `doc` will reflect the information inside the XML `doc`. Note that the `xref` keyword is only available in the `YAML` representation and will be transformed into its textual representation inside the `doc` text in `XML`.
```

2025-06-23 09:22 UTC, lukaspie commented
@RubelMozumder I think this PR is an excellent starting point for the paper and many of the materials here could be brought into the paper. For JOSS, it is also important to have good documentation, so getting this PR finished should be high on our priority list before submission.

2025-06-24 12:22 UTC, RubelMozumder commented on docs/tutorials.md
> +**NeXus choice in YAML format**
Commented out!

2025-06-24 12:37 UTC, RubelMozumder commented on docs/how_to_guide.md
> +```bash
Nice feature. Included.

2025-06-24 15:38 UTC, lukaspie commented on docs/index.md
> +- [How-to guide for nyaml tools](how_to_guide.md)
```suggestion
- [How-to guide for using the `nyaml` tools(how_to_guide.md)
```

2025-06-24 15:38 UTC, lukaspie commented on docs/index.md
> +- [Tutorials for writing NeXus definition in YAML](tutorials.md)
```suggestion
- [Writing a NeXus definition in YAML](tutorials.md)
```

2025-06-24 15:38 UTC, lukaspie commented on mkdocs.yml
> +  - Explanation: explanations.md
```suggestion
  - Explanation: explanations.md
  - Reference: references.md
```
swapping the order to have them in the same way as they are showing up on the main page

2025-06-24 15:38 UTC, lukaspie commented on .github/workflows/build_docs.yml
> +name: build_docs
Maybe we can align a bit more with the worfklow used in pynxtools: https://github.com/FAIRmat-NFDI/pynxtools/blob/master/.github/workflows/build_docs.yml

2025-06-24 15:38 UTC, lukaspie commented on README.md
>  9. [References](#references)
please remove this table of contents as well

2025-06-24 15:38 UTC, lukaspie commented on docs/index.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
Now that I see it here, maybe this is actually too much for the general index. If we build the docs, we have to scroll a lot to see the different tiles for the individual parts of the plugin. My bad!

My suggestion:
- for the index page, go with a smaller description of the tool (like we do in the NOMAD [docs](https://nomad-lab.eu/prod/v1/staging/docs/))
- Whatever does fit into this short introduction, move it back to the explanations.
- For this, I suggest that we have two pages in the explanations part:
  - One is an actual explanation of what the tool is for (i.e., the long text we now have in index.md) -> goes to explanations.md
  - The other is what we already have in the explanations section. This is concerned with the workflow, so I would move it to a new file called workflow.md
- Of course, the links in index.md and mkdocs.yml need to be updated afterwards.

Sounds okay?

2025-06-24 15:38 UTC, lukaspie commented on docs/index.md
> +
Add a third page here for the workflow, as described above

2025-06-24 15:38 UTC, lukaspie commented on docs/references.md
> +2. <a name="NeXus-FAIRmat"></a>[NeXus-FAIRmat](https://fairmat-experimental.github.io/nexus-fairmat-proposal/)
```suggestion
2. <a name="NeXus-FAIRmat proposal"></a>[NeXus-FAIRmat proposal](https://fairmat-experimental.github.io/nexus-fairmat-proposal/)
```

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +This tutorial will explain different keywords, terms and rules from the prespective of YAML format of the NeXus schema.
Note that tutorial, how-to guide, reference, etc. have special meaning in the [Diataxis framework](https://diataxis.fr/) we are using. This also means that the different sections should align with that meaning. But it's probably fine to keep it as is.

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +# Tutorials
Use a more descriptive title here. Tutorial for what?

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
Add line breaks, now it looks like a very big bloc in the built docs.

![image](https://github.com/user-attachments/assets/f0c46b8b-1988-4e84-8d0e-5564b3f3d25e)

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +
Here it is better with the linebreaks.

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +Descriptive information about NeXus groups is encapsulated within the `doc` child of the respective group. It is important to note that the group annotation of `source_TYPE(NXsource)` or `(NXsource)s
I think we are enforcing `source_TYPE(NXsource)` now, so this part can be dropped

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +A NeXus group may contain NeXus fields, NeXus attributes, and NeXus groups. A field, that does not have preceding `NX`, and a attribute, preceded by `\@`, must have a [NeXus type](https://manual.nexu
```suggestion
A NeXus group may contain NeXus fields, NeXus attributes, and other NeXus groups. A field, which is written as a string without a preceding `NX`, and an attribute, preceded by `\@`, must have a [NeXus type](https://manual.nexusformat.org/nxdl-types.html#index-0) (e.g.`NX_FLOAT`, `NX_CHAR`). The NeXus type type must be denoted inside parenthesis (e.g. `end_time(NX_DATE_TIME)`; if it is ommited, the NeXus field or attribute has the type `NX_CHAR` by default. Other XML attributes of the NeXus `field`/`attribute` can be defined using one of a set of special key ords below the field/attribute by indentation (the special keywords will be discussed in the next section). The explanatory documentation text of the NeXus field/attribute is given within the `doc` child.
```

Also make sure to either always use `field`/`attribute` (i.e., code-like) or just plain field/attribute.

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +A NeXus group may encompass multiple `field`, `attribute`, and subgroup, each serving distinct purposes within the data structure. The [`field`](https://manual.nexusformat.org/design.html#design-fiel
This can be removed, it is a repetition of the paragraph before.

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +Additionally, `XML` attributes specific to NeXus field and attribute are represented as children of the corresponding `field` or `attribute` elements (further details on special keywords will be disc
Remove as described above

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +The NeXus `link` concept reduces duplication of the data since several concepts of the same kind (e.g., NeXus field or NeXus attribute) can refer to a single copy of a data element. In YAML format, N
```suggestion
The NeXus `link` reduces data duplication since several concepts of the same kind (e.g., NeXus group, field, or attribute) can refer to a single copy of a data element. In YAML format, NeXus `link` is defined denoting the link in parenthesis. At the same time, the concept containing the data must be mentioned under the `target` child.
```

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +In the above YAML example, `reference_measurement` is defined as a link refering the `NXentry` group with its target specified as `/entry`. This structure ensures that the concept referencing the dat
```suggestion
In the YAML example above, `reference_measurement` is defined as a link refering to the `NXentry` group with its target specified as `/entry`. This structure ensures that the concept referencing the data is effectively linked to the designated target, thereby reducing redundancy and maintaining data integrity within the NeXus framework.
```

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +To explain the context of NeXus, certain keywords hold significance beyond their literal interpretations. These special keywords are utilized to elucidate and denote various NeXus terms like attribut
```suggestion
In the YAML schema the tool uses, certain keywords hold significance beyond their literal interpretations. These special keywords are utilized to elucidate and denote various NeXus terms like attributes, fields, links, and groups, thereby enhancing the clarity and specificity of the data representation.
```

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +The `exists` keyword plays a pivotal role in delineating the optionality of NeXus concepts `attribute`, `field`, `choice` `link`, and `group`, during the implementation of NeXus definitions in NeXus
remove choice here

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +The `exists` keyword plays a pivotal role in delineating the optionality of NeXus concepts `attribute`, `field`, `choice` `link`, and `group`, during the implementation of NeXus definitions in NeXus
```suggestion
The `exists` keyword plays a pivotal role in definining the optionality of NeXus concepts `attribute`, `field`, `link`, and `group`. It provides crucial insights into the expected presence or absence of these concepts within the NeXus data structure when implementing the NeXus definitions in NeXus files. By default, all the concepts of a base class are optional, while in an application definition, all concepts are required.
```

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +`required`: Indicates that the NeXus concept must be present within the structure. Any validation of a NeXus file will fail or give warning if required concepts (for a given application definition) a
```suggestion
`required`: Indicates that the NeXus concept must be present within the structure. Any validation of a NeXus file will fail or give a warning if required concepts (for a given application definition) are not available.
```

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +In the above example the greoup `transmission_correction` is a optional group.
```suggestion
In the above example the group `transmission_correction` is an optional group.
```

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +A statement introducing NeXus-compliant NXDL `units` attribute to the `field`, e.g. `NX_VOLTAGE` to assign a predefined physical unit.
```suggestion
The `unit` keyword is used to define the NeXus-compliant unit categories (which int the NXDL schema are denoted as `units`).
```

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +The `dimensions` term  describes the multidimensional nature of the data, specifying its rank, dimensional indices, and corresponding length of the rank. For example, the attribute `rank` defines the
```suggestion
The `dimensions` term  describes the multidimensional nature of the data, specifying its rank, dimensional indices, and corresponding length of the rank. The attribute `rank` defines the dimension of the data set. To elucidate each dimension, we use two other keywords: `dim` and `dim_parameters`. The `dim` keyword comprises an array of arrays, the nested array encapsulates values for `index` and `value` (NeXus keywords) pairs. Each array within the `dim` array corresponds to a specific dimension of the multidimensional data. For example, for 2D particle motion, the `dim` array may be represented as `[[0, nx], [1, ny]]`, each member indicating the axis index and axis name. The keyword `dim_parameters` contains further information of each dimension such as `doc`, `ref`, etc. It is important to note that each term or keyword within `dim_parameters` must have the same length as the value of the rank keyword.
```

This reads a bit confusing, but probably okay

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +Python-like list of strings which are considered as recommended items for the fields or attributes.
```suggestion
List of strings which are considered as a set of predefined values for fields or attributes.
```

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +Python-like list of strings which are considered as recommended items for the fields or attributes.
Add something about open enums here.

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +The `xref` keyword (which can only be used inside the keyword `doc`) is used to refer any other ontology or any other standard such `ISO`. The `xref` in the example `doc` will reflect the information
Remove the part starting from "The `xref` keyword", this is mentioned in the next section

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +The `xref` keyword (which can only be used inside the keyword `doc`) is used to refer any other ontology or any other standard such `ISO`. The `xref` in the example `doc` will reflect the information
```suggestion
The `xref` keyword (which can only be used inside the keyword `doc`) is used to refer any other ontology or any other standard (such as `ISO`). The `xref` in the example `doc` will reflect the information inside the XML `doc`. Note that the `xref` keyword is only available in the `YAML` representation and will be transformed into its textual representation inside the `doc` text in `XML`.
```

2025-06-24 15:38 UTC, lukaspie commented on docs/tutorials.md
> +### Keyword `nameType`
I would push this up, right to where we are discussing the name and the replacement if nameType is partial or any

2025-06-25 07:19 UTC, mkuehbach commented on docs/explanations.md
> +For a given input file, the `nyaml` converter checks for the correct file type and call appropriate converter. For an XML file, the `nxdl2yaml` converter parses the `XML` file, by means of [lxml](htt
"Provided an input file, the `nyaml` converter ..... and calls one of two possible converters: For an `nxdl.xml` file this is the `nxdl2yaml` converter. For a `yaml`file this is the `yaml2nxdl` converter.

for the sentence with lxml reformulate "The lxml Python library (add proper ref) is used for parsing XML files into an `XML` tree object in memory."

2025-06-25 07:20 UTC, mkuehbach commented on docs/explanations.md
> +Like every scientific software, the `nyaml` tool also follows a specific workflow.
reformulate and shorten: "`nyaml` implements a specific workflow:"

2025-06-25 07:21 UTC, mkuehbach commented on docs/explanations.md
> +```mermaid
If we want such mermaid plot in the JOSS CI/CD?
If not, we should export a vector graphic beforehand.

2025-06-25 07:24 UTC, mkuehbach commented on docs/explanations.md
> +Presented below is a concise and trimmed example of the `NXmpes` application definition (for discussion purpose) in `YAML` format, alongside its corresponding encoding into `XML` format, as illustrat
The part "NOTE: For in" should be moved to a highlighting box that are used also in other places and plugins in NOMAD

2025-06-25 07:28 UTC, mkuehbach commented on docs/explanations.md
> +Presented below is a concise and trimmed example of the `NXmpes` application definition (for discussion purpose) in `YAML` format, alongside its corresponding encoding into `XML` format, as illustrat
this is a part in the learning section following the diataxis paradigm I do not really get why at all here a full excerpt of an application definition is shown, if we show one show a shorter one that has the complexities in it but is not as long, 
but also nothing is here really explained just the result of the nxdl to yaml conversion is presented without substantiated explanation.

2025-06-25 07:28 UTC, mkuehbach commented on docs/explanations.md
> +    exsits: required
this is for sure wrong

2025-06-25 07:28 UTC, mkuehbach commented on docs/explanations.md
> +      \@version:
this as well intendation

2025-06-25 07:30 UTC, mkuehbach commented on docs/explanations.md
> +    title:
having on example like

a_char_concept(NX_CHAR)

and another one with

another_char_concept:

is useful indeed in an explanation if complemented with the explanation that because NX_CHAR is assumed the default writing NX_CHAR can be omitted. This is though the only type that can be omitted, which should also be stated.

2025-06-25 07:30 UTC, mkuehbach commented on docs/explanations.md
> +    exsits: required
we must not share incorrect explanations!

2025-06-25 07:33 UTC, mkuehbach commented on docs/explanations.md
> +        xref:
this for sure substantiates to have an explanation

my proposal is to split the individual snippets of the appdef apart and have one code snippet per feature but then this qualifies for moving it into the references.md

2025-06-25 07:34 UTC, mkuehbach commented on docs/explanations.md
> +      source_TYPE(NXsource):
this for sure warrants explanation given that we have now nameType any capitalization is no longer decisive when it comes to defining if a concept name has variadic parts or not

2025-06-25 07:34 UTC, mkuehbach commented on docs/explanations.md
> +```
this should be splitted

2025-06-25 07:36 UTC, mkuehbach commented on docs/explanations.md
> +
the functionality of nyaml that there is a caching in the sense that the source XML is attached to the tail of an yaml file should be explained and ideally get a small example snippet, it is important to mention that a hashing is used for figuring out if content changed

2025-06-25 07:37 UTC, mkuehbach commented on docs/how_to_guide.md
> +`nyaml` is a Python package [published on PyPI](https://pypi.org/project/nyaml/).
"that is [published on PyPI]"

2025-06-25 07:38 UTC, mkuehbach commented on docs/how_to_guide.md
recommend to change filename to "howto.md"

2025-06-25 07:38 UTC, lukaspie commented on docs/explanations.md
> +```mermaid
We need to check that it builds correctly using the mkdocs CI/CD, right? JOSS CI/CD is just for the paper draft.

That being said, in the current docs, it looks like this
![image](https://github.com/user-attachments/assets/49030c1b-f961-4dd0-9b74-22186dc431ed)

Is that how it's supposed to look? If not, converting to a graphic may be nicer.

2025-06-25 07:41 UTC, mkuehbach commented on docs/index.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
"dartawhat does the "It" in "data principles. It" refer to?

2025-06-25 07:43 UTC, mkuehbach commented on docs/index.md
> +NXDL is used to define general data storage objects (base classes) and the base classes are the building blocks for defining measurement-specific or even instrument-specific or software-specific data
Adding to Lukas' recommendation I suggest to do the splitting first and then start a revisioning of the text paragraph snippets remaining, for this reason I skip the revision here for this file.

2025-06-25 07:45 UTC, mkuehbach commented on docs/references.md
> +4. <a name="official site"></a>[Official NeXus website](https://manual.nexusformat.org/index.html)
"official site" > "Official NeXus website"

2025-06-25 07:45 UTC, mkuehbach commented on docs/references.md
> +5. <a name="j_appl_cryst_2015"></a>[J. Appl. Cryst. (2015). 48, 301-305](https://doi.org/10.1107/S1600576714027575)
"j_appl_cryst_2015" > "Könnecke, M. et al."

2025-06-25 07:46 UTC, mkuehbach commented on docs/references.md
> +11. <a name="NeXus Manual"></a>[NeXus Manual](https://manual.nexusformat.org/user_manual.html)
we should check that all these links are still working

2025-06-25 07:47 UTC, mkuehbach commented on docs/references.md
> +10. <a name="lxml"></a>[lxml](https://lxml.de/)
Follow these rules:
http://citebay.com/how-to-cite/lxml/

2025-06-25 07:48 UTC, mkuehbach commented on docs/stylesheets/extra.css
does this implement the latest corporate design which e.g. pynxtools is using as well, if not, make a specific PR for changing this that can be merged into src branch of this PR

2025-06-25 07:51 UTC, mkuehbach commented on docs/tutorials.md
> +This explanatory tutorial will explain different keywords, terms, and rules from the perspective of YAML format of the NeXus schema. Therefore it provides a overall grasp on how to write a NeXus sche
Paragraph needs to be completely rewritten.

On the one hand for grammar and language.
On the other hand for precision of the formulations,
a NeXus data schema's XML schema may have a serialization in YAML but other than this there is no connection between NeXus and YAML.

2025-06-25 07:56 UTC, mkuehbach commented on docs/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
This paragraph is an enumeration of mappings between where something is in XML and where it is in yaml and vice versa, the content should be splitted in shorter paragraphs, statements about what is in the top-level section should go to a paragraph on top-level section, statements for a appdefs going into one in appdefs.

This is a tutorial, meaning taking people by the hand, a wall of mappings provides no taking by some hand, currently not enough bandwidth to edit this on the train

maybe its an approach to do first the moving of content like suggested by Lukas and then make individual follow-up PRs e.g. one for each md file, explanations, howto,
this would enable a more focused "head writing" and makes the reviewing shorter instead of trying to lump all changes in one PR

2025-06-25 07:59 UTC, mkuehbach commented on docs/tutorials.md
> +A NeXus group may contain NeXus fields, NeXus attributes, and NeXus groups. A field, that does not have preceding `NX`, and a attribute, preceded by `\@`, must have a [NeXus type](https://manual.nexu
There is here for me too much giving references to things and overall too much stuff in that flat file, better make tutorial.md have an own table of concepts so that one can navigate from section to section, also making reference to specific locations in the NeXus manual we should use whenever possible

2025-06-25 08:03 UTC, mkuehbach requested changes
Implement the suggestions from Lukas first, especially the splitting and moving of content, apply then my comments on top

2025-06-26 15:41 UTC, RubelMozumder commented on docs/tutorials.md
> +Descriptive information about NeXus groups is encapsulated within the `doc` child of the respective group. It is important to note that the group annotation of `source_TYPE(NXsource)` or `(NXsource)s
Yeah, but I do not give any stress on any specific way of dynamic innitialisation, both `(nx_class)` and `static_nameDANYMICNAMNE`, both should come into the picture, no?

2025-06-26 16:23 UTC, lukaspie commented on docs/tutorials.md
> +Descriptive information about NeXus groups is encapsulated within the `doc` child of the respective group. It is important to note that the group annotation of `source_TYPE(NXsource)` or `(NXsource)s
My point is that we never write `(NXsource)source_TYPE` anymore, so we should not mention it herr

2025-06-27 07:12 UTC, RubelMozumder commented on docs/tutorials.md
> +The `dimensions` term  describes the multidimensional nature of the data, specifying its rank, dimensional indices, and corresponding length of the rank. For example, the attribute `rank` defines the
Added in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:13 UTC, RubelMozumder commented on docs/tutorials.md
> +The `xref` keyword (which can only be used inside the keyword `doc`) is used to refer any other ontology or any other standard such `ISO`. The `xref` in the example `doc` will reflect the information
Added in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:14 UTC, RubelMozumder commented on docs/references.md
> +2. <a name="NeXus-FAIRmat"></a>[NeXus-FAIRmat](https://fairmat-experimental.github.io/nexus-fairmat-proposal/)
Added in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:16 UTC, RubelMozumder commented on docs/tutorials.md
> +A NeXus group may contain NeXus fields, NeXus attributes, and NeXus groups. A field, that does not have preceding `NX`, and a attribute, preceded by `\@`, must have a [NeXus type](https://manual.nexu
Added in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:17 UTC, RubelMozumder commented on docs/tutorials.md
> +A NeXus group may encompass multiple `field`, `attribute`, and subgroup, each serving distinct purposes within the data structure. The [`field`](https://manual.nexusformat.org/design.html#design-fiel
Added in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:17 UTC, RubelMozumder commented on docs/tutorials.md
> +The NeXus `link` concept reduces duplication of the data since several concepts of the same kind (e.g., NeXus field or NeXus attribute) can refer to a single copy of a data element. In YAML format, N
Addressed in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:18 UTC, RubelMozumder commented on docs/tutorials.md
> +To explain the context of NeXus, certain keywords hold significance beyond their literal interpretations. These special keywords are utilized to elucidate and denote various NeXus terms like attribut
Addressed in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:18 UTC, RubelMozumder commented on docs/tutorials.md
> +The `exists` keyword plays a pivotal role in delineating the optionality of NeXus concepts `attribute`, `field`, `choice` `link`, and `group`, during the implementation of NeXus definitions in NeXus
Addressed in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:19 UTC, RubelMozumder commented on docs/tutorials.md
> +`required`: Indicates that the NeXus concept must be present within the structure. Any validation of a NeXus file will fail or give warning if required concepts (for a given application definition) a
Addressed in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:19 UTC, RubelMozumder commented on docs/tutorials.md
> +A statement introducing NeXus-compliant NXDL `units` attribute to the `field`, e.g. `NX_VOLTAGE` to assign a predefined physical unit.
Addressed in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:33 UTC, RubelMozumder commented on docs/tutorials.md
> +Descriptive information about NeXus groups is encapsulated within the `doc` child of the respective group. It is important to note that the group annotation of `source_TYPE(NXsource)` or `(NXsource)s
Yeah, we do not write a group in that way if we develop from scratch. It is still writeable and indeed we get such syntax while extending or converting other nxdl file to yaml file developed by external people.

It is not anything wrong, right? IMO, by removing that we mainly hiding the another way of group representation in yaml which may be appeared in several app def or base class.

you may rethink that, I can remove that part, no problem.

2025-06-27 07:35 UTC, RubelMozumder commented on docs/tutorials.md
> +Additionally, `XML` attributes specific to NeXus field and attribute are represented as children of the corresponding `field` or `attribute` elements (further details on special keywords will be disc
Addressed in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:35 UTC, RubelMozumder commented on docs/tutorials.md
> +In the above YAML example, `reference_measurement` is defined as a link refering the `NXentry` group with its target specified as `/entry`. This structure ensures that the concept referencing the dat
Addressed in [5ec2c7b](https://github.com/FAIRmat-NFDI/nyaml/commit/5ec2c7b07b738aac1a483248431b410e0c8577f8)

2025-06-27 07:36 UTC, RubelMozumder commented on docs/tutorials.md
> +The `exists` keyword plays a pivotal role in delineating the optionality of NeXus concepts `attribute`, `field`, `choice` `link`, and `group`, during the implementation of NeXus definitions in NeXus
commented out.

2025-06-30 06:47 UTC, RubelMozumder commented on .github/workflows/build_docs.yml
> +name: build_docs
Addressed at 53d263ed5edd4ec3ca20fb55b07674980f8d137e.

2025-06-30 06:47 UTC, RubelMozumder commented on .github/workflows/build_docs.yml
> +name: build_docs
Addressed at 53d263ed5edd4ec3ca20fb55b07674980f8d137e

2025-06-30 06:47 UTC, RubelMozumder commented on docs/index.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
Addressed at 53d263ed5edd4ec3ca20fb55b07674980f8d137e

2025-06-30 06:48 UTC, RubelMozumder commented on docs/tutorials.md
> +# Tutorials
Addressed at 53d263ed5edd4ec3ca20fb55b07674980f8d137e

2025-06-30 06:49 UTC, RubelMozumder commented on README.md
>  9. [References](#references)
Addressed at 53d263ed5edd4ec3ca20fb55b07674980f8d137e

2025-06-30 06:53 UTC, RubelMozumder commented
Do a final check if all links work!

2025-06-30 06:56 UTC, RubelMozumder commented on docs/tutorials.md
> +Descriptive information about NeXus groups is encapsulated within the `doc` child of the respective group. It is important to note that the group annotation of `source_TYPE(NXsource)` or `(NXsource)s
Addressed in 79eabd68751c64902af81894c0d684b2a8c280d3.

2025-06-30 07:36 UTC, RubelMozumder commented on docs/references.md
> +10. <a name="lxml"></a>[lxml](https://lxml.de/)
This is not a citation as goes with publication. But a general reference link used software or information. Or? But the such citation must come in Joss paper as you mentioned in here.

2025-06-30 08:03 UTC, lukaspie commented
Thanks for splitting the explanations and workflow parts. I think for editability in the future it may be good to have separate folders for the 4 diataxis groups (tutorial, learn, etc.) into which we place the respective files.

2025-06-30 08:19 UTC, lukaspie reviewed
Couple more comments, already going in the right direction

2025-06-30 08:19 UTC, lukaspie commented on docs/explanations.md
> +# NeXus Definition Language (NXDL), XML, and YAML
Would move the "At its core, the NeXus Definition Language (NXDL)..." sentence to the start of the next paragraph

2025-06-30 08:19 UTC, lukaspie commented on docs/explanations.md
> +NXDL is used to define general data storage objects (base classes) and the base classes are the building blocks for defining, under the schema called application definition,  measurement-specific or
```suggestion
NXDL is used to define general data structures (base classes), which define the set of terms that might be used in an instance of that class. These base classes are the building blocks for defining, under the schema called application definition, measurement-specific or even instrument-specific or software-specific data storage objects. In this process, members and definitions of individual base classes can be used as is or customized. In essence, the process of schema development, whether for a base class or an application definition, entails crafting an NXDL schema definition file with the extension 'nxdl.xml', utilizing the Extensible Markup Language, [XML](https://www.w3.org/TR/REC-xml/REC-xml-20081126.xml).
```

We do not define data storage objects!

2025-06-30 08:19 UTC, lukaspie commented on docs/explanations.md
> +To expedite the schema development process, we have introduced the use of Yet Another Markup Language ([YAML](https://yaml.org/)), which provides a syntax or style specifically tailored for defining
```suggestion
To expedite the schema development process, we have introduced the use of Yet Another Markup Language ([YAML](https://yaml.org/)), which provides a syntax or style specifically tailored for defining scientific domain-driven schemas with NXDL. One significant advantage of YAML over XML is its indentation-driven approach, which eliminates the need for starting and ending tags for each entity within the schema. The YAML format reduces repetition of NXDL keywords and offers a more intuitive structure aligned with object-oriented programming concepts, such as class inheritance. These benefits are attained without compromising the integrity of the original NeXus schema, which is traditionally expressed in XML format.
```

always use either YAML or `YAML` (i.e., plain text or code)

2025-06-30 08:19 UTC, lukaspie commented on docs/explanations.md
> +The `YAML` format, while not yet an official version of NeXus application definitions or base classes, necessitates a method for transcoding it into `XML`. The [nyaml](https://github.com/FAIRmat-NFDI
```suggestion
While `YAML` offers a more readable and concise way to author NeXus definitions, a transcoding mechanism is required because the official format remains XML. The [nyaml](https://github.com/FAIRmat-NFDI/nyaml) Python package serves as a converter tool designed specifically for this purpose. It enables the conversion of NXDL-compliant definitions from YAML to XML, making it easier for NeXus schema developers to create and maintain definitions. Furthermore, the tool offers the flexibility to extend existing NeXus schemas in XML by facilitating conversion back and forth between the two formats. It is important to note that here we do not introduce NeXus data objects, terms, or types, which are fundamental for writing base class schemas or application definition schemas. For individuals new to NeXus, we refer to the official NeXus site at NeXus ([NeXus official website](https://www.nexusformat.org/)).
```

2025-06-30 08:19 UTC, lukaspie commented on docs/index.md
> +The tool can be installed via pip, and it provides comprehensive documentation and tutorials to assist users in writing NeXus definitions in `YAML`.
```suggestion
The `nyaml` tool offers a user-friendly command-line interface for converting between `YAML` and `XML` representations of NeXus definitions written in the NeXus Definition Language (NXDL). While the official NeXus definitions are maintained in `XML,` authoring them in `YAML` provides a more concise and readable alternative. `nyaml` bridges this gap, allowing developers to work in `YAML` while ensuring compatibility with the official `XML` format.

The tool supports both application definitions and base classes. It can be installed via `pip` and includes comprehensive documentation and tutorials to assist users in writing NeXus definitions using `YAML`.
```

We should mention what the package solves at the beginning.

2025-06-30 08:19 UTC, lukaspie commented on docs/index.md
> +- [Use of `nyaml` tool](how_to_guide.md)
```suggestion
- [Installation and use of the `nyaml` tool](how_to_guide.md)
```

2025-06-30 08:19 UTC, lukaspie commented on docs/index.md
> +An introduction to NeXus and its design principles.
Remove this sentence, it does not match the individual pages

2025-06-30 11:46 UTC, RubelMozumder commented on docs/explanations.md
> +For a given input file, the `nyaml` converter checks for the correct file type and call appropriate converter. For an XML file, the `nxdl2yaml` converter parses the `XML` file, by means of [lxml](htt
Tailored!

2025-06-30 11:50 UTC, RubelMozumder commented on docs/explanations.md
> +    exsits: required
Addresed!

2025-06-30 11:56 UTC, RubelMozumder commented on docs/explanations.md
> +      source_TYPE(NXsource):
Explained with nameType.

2025-06-30 11:57 UTC, RubelMozumder commented on docs/how_to_guide.md
Addressed!

2025-06-30 12:00 UTC, RubelMozumder commented on docs/index.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
Addresed!

2025-06-30 14:14 UTC, RubelMozumder commented on docs/index.md
> +An introduction to NeXus and its design principles.
Modified!

2025-06-30 14:29 UTC, RubelMozumder commented on docs/explanations.md
> +NXDL is used to define general data storage objects (base classes) and the base classes are the building blocks for defining, under the schema called application definition,  measurement-specific or
Addressed!

2025-06-30 14:30 UTC, RubelMozumder commented on docs/explanations.md
> +To expedite the schema development process, we have introduced the use of Yet Another Markup Language ([YAML](https://yaml.org/)), which provides a syntax or style specifically tailored for defining
Addressed!

2025-06-30 14:30 UTC, RubelMozumder commented on docs/explanations.md
> +The `YAML` format, while not yet an official version of NeXus application definitions or base classes, necessitates a method for transcoding it into `XML`. The [nyaml](https://github.com/FAIRmat-NFDI
Addresseds!

2025-06-30 14:31 UTC, RubelMozumder commented on docs/index.md
> +The tool can be installed via pip, and it provides comprehensive documentation and tutorials to assist users in writing NeXus definitions in `YAML`.
Addressed!

2025-06-30 14:31 UTC, RubelMozumder commented on docs/index.md
> +- [Use of `nyaml` tool](how_to_guide.md)
Addressed!

2025-06-30 14:32 UTC, RubelMozumder commented on docs/explanations.md
> +# NeXus Definition Language (NXDL), XML, and YAML
Addressed!

2025-06-30 15:13 UTC, lukaspie commented on mkdocs.yml
> +  # homepage: https://fairmat-nfdi.github.io/pynxtools/
should be nyaml

2025-07-01 07:22 UTC, RubelMozumder commented on mkdocs.yml
> +  # homepage: https://fairmat-nfdi.github.io/pynxtools/
fixed!

2025-07-03 10:47 UTC, mkuehbach approved these changes
All remaining conversations have been resolved, the PR is already quite long, the CI runs through, this PR should be merged @RubelMozumder

2025-07-08 15:24 UTC, lukaspie requested changes
Mostly typos/grammar corrections, but also some things about the documentation build using mkdocs need to be changed

2025-07-08 15:24 UTC, lukaspie commented on mkdocs.yml
> +  - Reference: references/references.md
This sections needs to be updated so that the new pages are included in the left-hand side navigation

2025-07-08 15:24 UTC, lukaspie commented on mkdocs.yml
> +  The documentation for the NYAML tool which is a converter tool to transcode NeXus schema from YAML to XML (.nxdl.xml).
```suggestion
  Documentation for nyaml: a converter tool to transcode NeXus schemas from YAML to XML (.nxdl.xml).
```

2025-07-08 15:24 UTC, lukaspie commented on pyproject.toml
> +    # Mkdocs and the related plugins
I suggest to make these their own `docs` extra, like in pynxtools

2025-07-08 15:24 UTC, lukaspie commented on src/nyaml/comment_collector.py
> +class YAMLComment(Comment):  # noqa: PLW1641
I beleive this is no longer neccessary

2025-07-08 15:24 UTC, lukaspie commented on README.md
> +Check full documentation of the tool in [gh] https://fairmat-nfdi.github.io/nyaml/
```suggestion
You can find the full documentation of the tool [here](https://fairmat-nfdi.github.io/nyaml/)
```
gh does not mean anything to new users

2025-07-08 15:24 UTC, lukaspie commented on docs/assets/.gitignore
> +nomad-oasis*.zip
Is this needed?

2025-07-08 15:24 UTC, lukaspie commented on mkdocs.yml
> +  logo: assets/nomad-plugin-logo.png
This is not a NOMAD plugin, so we should not use the NOMAD plugin logo. Can we just use a regular NOMAD logo? If not, I suggest we don't use any logo at all.

2025-07-08 15:24 UTC, lukaspie commented on mkdocs.yml
> +  - pymdownx.emoji: # TODO make sure this isn't used!!
Can you double check that this is needed for the docs to build?

2025-07-08 15:24 UTC, lukaspie commented on docs/references/references.md
> +#References
```suggestion
# References
```

2025-07-08 15:24 UTC, lukaspie commented on docs/learn/workflow.md
> +The `nyaml` implements a specific workflow for converting between YAML and XML formats. The `nyaml` converter checks for the correct file type and calls the appropriate converter. For an XML file, th
```suggestion
`nyaml` implements a specific workflow for converting between YAML and XML formats. The `nyaml` converter checks for the correct file type and calls the appropriate converter. For an XML file, the `nxdl2yaml` converter parses the `XML` file, by means of the [lxml](https://lxml.de/) Python library, into an `XML` tree object. Adhering to the NXDL rules, the converter writes the application definition or the base class object to a `YAML` file that matches the `nyaml` syntax. If the input file is a `YAML` file, the `yaml2nxdl` converter collects the comments in a `Comments` object and parses the `YAML` file into a python `dictionary` object. Afterwards, the application definitions or base classes is converted into an `XML` file by combining the `Comments` and the Python `dictionary` object.
```

2025-07-08 15:24 UTC, lukaspie commented on docs/learn/workflow.md
> +After the conversion from `XML` format to `YAML` format, the `nyaml` tool stores the `XML` contents at the end of the file under a hash created by Secure Hash Algorithm sha256 from `YAML` contents ge
```suggestion
After the conversion from `XML` format to `YAML` format, the `nyaml` tool stores the `XML` contents at the end of the file under a hash created by Secure Hash Algorithm sha256 from `YAML` contents generated in this conversion process. This benefits the backward compatibility of the `YAML` file, so that the `YAML` file can be converted back to `XML` file without any modification of structure like whitespaces or newlines.
```

2025-07-08 15:24 UTC, lukaspie commented on docs/learn/workflow.md
> +Presented below is a concise and trimmed example of the `NXmpes` application definition (for discussion purpose) in `YAML` format, alongside its corresponding encoding into `XML` format, as illustrat
Can we link to NXmpes here?

2025-07-08 15:24 UTC, lukaspie commented on docs/learn/workflow.md
> +    For indetailed explanation with examples please follow the [Tutorials for writing NeXus definition in YAML](../tutorials/tutorials.md).
```suggestion
    For a detailed explanation with examples please follow the [tutorial for writing NeXus definition in YAML](../tutorials/tutorials.md).
```

2025-07-08 15:24 UTC, lukaspie commented on docs/learn/workflow.md
> +    The `NXmpes` application is an old and trimmed version which does not serve any scientific purpose, but only is used to illustrate the results of the conversion process.
```suggestion
    The application definition used here is an old and trimmed version of `NXmpes`  which does not serve any scientific purpose, but is only used to illustrate the results of the conversion process.
```

```suggestion
    The application definition used here is an old and trimmed version of `NXmpes`  which does not serve any scientific purpose, but is only used here to illustrate the results of the conversion process.
```

2025-07-08 15:24 UTC, lukaspie commented on docs/learn/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
```suggestion
The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those engaged in neutron, X-ray, and muon research (see the most recent NeXus paper by [Könnecke et al.](https://doi.org/10.1107/S1600576714027575)). The data format is also used by the material science community under the project [NeXus-FAIRmat proposal](https://fairmat-experimental.github.io/nexus-fairmat-proposal/) supporting FAIR (Findable, Accessible, Interoperable and Reuseable) data principles in material science. The format serves as a standardized framework for both data exchange and storage.
```

2025-07-08 15:24 UTC, lukaspie commented on docs/index.md
> +- [Workflow of the nyaml tool with examples](learn/workflow.md)
These must be added to the mkdocs.yaml file in the `nav` section

2025-07-08 15:24 UTC, lukaspie commented on docs/references/references.md
> +5. <a name="Könnecke, M. et al."></a>[Könnecke, M. et al.](https://doi.org/10.1107/S1600576714027575)
```suggestion
5. <a name="NeXus paper by Könnecke et al."></a>[NeXus paper by Könnecke et al.](https://doi.org/10.1107/S1600576714027575)
```

2025-07-08 15:24 UTC, lukaspie requested changes
Mostly typos/grammar corrections, but also some things about the documentation build using mkdocs need to be changed

2025-07-11 07:12 UTC, mkuehbach commented on docs/assets/nomad-plugin-logo.png
We should just go with the left part of the logo, i.e. the favicon, as nyaml is a standalone activitity rather than a NOMAD plugin. There is no entry point handling in nyaml.

We should also add the NeXus logo here, i.e. either this
https://github.com/nexusformat/NIAC/blob/master/NeXus_Logo/NeXus_Logo.svg or this
https://github.com/nexusformat/NIAC/blob/master/NeXus_Logo/NeXus_Logo_square.svg
Personally leaning to the second one could place it right next to the NOMAD Logo

2025-07-11 07:14 UTC, mkuehbach commented on docs/howtos/howto.md
> +# nyaml Installation and Command
Getting started with nyaml

2025-07-11 07:15 UTC, mkuehbach commented on docs/howtos/howto.md
> +The tool is published to `PyPI` and available for pip install
First part of the sentence is redundant suggestion > "To use the tool as is, you should run:"

2025-07-11 07:20 UTC, mkuehbach commented on docs/howtos/howto.md
> +## How to Install nyaml
I can even see this working without mentioning always nyaml, i.e. "How to install"
"How to use"

2025-07-11 07:20 UTC, mkuehbach commented on docs/howtos/howto.md
> +## How to Use the nyaml Tool
See above "How to use"

2025-07-11 07:22 UTC, mkuehbach commented on docs/howtos/howto.md
> +`nyaml` works as a command line tool to convert NeXus application definitions or base classes from `yaml` file format into the `nxdl.xml` file format and vice-versa. The converter can be called by th
from the `nxdl.xml` format to the `yaml` format and vice-versa.

i.e. I suggest to swop the order, typically one starts with a XML file as XML is still the preferred format by the NIAC.

2025-07-11 07:30 UTC, mkuehbach commented on docs/howtos/howto.md
> +The `--output-file` option defines the output file name (including the fle extension), otherwise the converter will define the output file name from the input file, e.g., for a input file `NXapplicat
"fle" > "file"
", otherwise" > ". If this option is  not provided, the converter will ..."
"output file name from the input file" > "output file name from the input file name"

", e.g., ... ". Exemplified for an input file named "NXapplication.nxdl.xml", the resultant file will be named ...

Line break before "With the option --check-consistency"

"*the nyaml produces" > "nyaml produces"
for an input file

2025-07-11 07:30 UTC, mkuehbach commented on docs/howtos/howto.md
> +The `--output-file` option defines the output file name (including the fle extension), otherwise the converter will define the output file name from the input file, e.g., for a input file `NXapplicat
"nxdl.xml" instead of "nxd.xml"

2025-07-11 07:31 UTC, mkuehbach commented on docs/howtos/howto.md
> +The `--output-file` option defines the output file name (including the fle extension), otherwise the converter will define the output file name from the input file, e.g., for a input file `NXapplicat
"The intention for this option is to verify proper conversion and version conversion of the file." required?

"proper conversion and version conversion" reads a bit weird to me

2025-07-11 07:33 UTC, mkuehbach commented on docs/howtos/howto.md
> +The `--output-file` option defines the output file name (including the fle extension), otherwise the converter will define the output file name from the input file, e.g., for a input file `NXapplicat
The option `--do-not-store-nxdl` prevents the `yaml` file from storing the original `nxdl.xml` text as comment.

We should tell that the default is that the XML part is added in the butt.
Then one can state. -do-not-store-nxdl deactivates the addition of the NXDL XML representation to the tail of the YAML file.

2025-07-11 07:35 UTC, mkuehbach commented on docs/index.md
> +# FAIRmat nyaml documentation
Wouldnt mention FAIRmat here but in the footer where indeed we should acknowledge the funding of the DFG

See an example here:
https://fairmat-nfdi.github.io/pynxtools-em/
bottom of the page with hyperlink to DFG page

2025-07-11 07:36 UTC, mkuehbach commented on docs/index.md
> +# FAIRmat nyaml documentation
Maybe also a statement supported by the NIAC is useful

2025-07-11 07:37 UTC, mkuehbach commented on docs/index.md
> +The `nyaml` tool offers a user-friendly command-line interface for converting between `YAML` and `XML` representations of NeXus definitions written in the NeXus Definition Language (NXDL). While the
`XML` and `YAML` representations

2025-07-11 07:40 UTC, mkuehbach commented on docs/index.md
> +The tool supports both application definitions and base classes. It can be installed via `pip` and includes comprehensive documentation and tutorials to assist users in writing NeXus definitions usin
"The tool supports both application definitions and base classes." why to mention it when it supports all classes?

2025-07-11 07:42 UTC, mkuehbach commented on docs/learn/explanations.md
hyperlink to https://yaml.org/ when writing YAML upon first occurance

2025-07-11 07:45 UTC, mkuehbach commented on docs/learn/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
Supporting the rewriting, we must not point though to outdated links.
Therefore, use [FAIRmat-NFDI ](https://github.com/FAIRmat-NFDI/nexus_definitions) instead of the fairmat-experimental -ish

2025-07-11 07:45 UTC, mkuehbach commented on docs/learn/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
"Interoperable, and Reusable"

2025-07-11 07:46 UTC, mkuehbach commented on docs/learn/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
Drop "data" in front of "principles"

2025-07-11 07:46 UTC, mkuehbach commented on docs/learn/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
Add Wilkinson and Jacobsen paper when mentioning FAIR

2025-07-11 07:48 UTC, mkuehbach commented on docs/learn/explanations.md
> +At the NeXus data format's core, the NeXus Definition Language (NXDL) functions as the cornerstone through which scientists delineate the nomenclature and organizational structure of information with
"The NeXus Definition Language (NXDL) at the core of the NeXus data format functions as ..."

2025-07-11 07:48 UTC, mkuehbach commented on docs/learn/explanations.md
> +At the NeXus data format's core, the NeXus Definition Language (NXDL) functions as the cornerstone through which scientists delineate the nomenclature and organizational structure of information with
"cornerstone through which" > "whereby"

2025-07-11 07:48 UTC, mkuehbach commented on docs/learn/explanations.md
> +At the NeXus data format's core, the NeXus Definition Language (NXDL) functions as the cornerstone through which scientists delineate the nomenclature and organizational structure of information with
pieces of information

2025-07-11 07:49 UTC, mkuehbach commented on docs/learn/explanations.md
> +At the NeXus data format's core, the NeXus Definition Language (NXDL) functions as the cornerstone through which scientists delineate the nomenclature and organizational structure of information with
personally would remove ", tailored to ..." cuz NXDL is always used irrespective if class was tailored or not

2025-07-11 07:53 UTC, mkuehbach commented on docs/learn/explanations.md
> +At the NeXus data format's core, the NeXus Definition Language (NXDL) functions as the cornerstone through which scientists delineate the nomenclature and organizational structure of information with
remove comma before [XML]

2025-07-11 07:59 UTC, mkuehbach commented on docs/learn/explanations.md
> +To expedite the schema development process, we have introduced the use of Yet Another Markup Language ([YAML](https://yaml.org/)), which provides a syntax or style specifically tailored for defining
"we have introduced the use of" > "recent the use of ... was introduced"

"The YAML format reduces repetition of NXDL keywords and offers a" > "Thus, using YAML reduces repetition of NXDL keywords and offers a"

2025-07-11 08:01 UTC, mkuehbach commented on docs/learn/explanations.md
> +While `YAML` offers a more readable and concise way to author NeXus definitions, a transcoding mechanism is required because the official format remains XML. The [nyaml](https://github.com/FAIRmat-NF
"designed specifically for" > "for specifically"

2025-07-11 08:03 UTC, mkuehbach commented on docs/assets/nomad-plugin-logo.png
Remove then this NOMAD plugin figure

2025-07-11 08:03 UTC, mkuehbach commented on docs/assets/.gitignore
> +nomad-oasis*.zip
Seems some debris left from hotfixing in the past, so no

2025-07-11 08:04 UTC, mkuehbach commented on docs/references/references.md
> +2. <a name="NeXus-FAIRmat proposal"></a>[NeXus-FAIRmat proposal](https://fairmat-experimental.github.io/nexus-fairmat-proposal/)
We must no longer point to this outdated experimental-ish resource, instead please point to FAIRmat-NFDI/nexus_definitions

2025-07-11 08:06 UTC, mkuehbach commented on docs/references/references.md
> +6. <a name="XML"></a>[XML](https://www.w3.org/TR/REC-xml/REC-xml-20081126.xml)
<a name="XML specification"></a>[XML specification](https://www.w3.org/TR/REC-xml/REC-xml-20081126.xml)

2025-07-11 08:07 UTC, mkuehbach commented on docs/references/references.md
> +9. <a name="YAML"></a>[YAML](https://yaml.org/)
<a name="Yet Another Markup Language YAML"></a>[Yet Another Markup Language YAML](https://yaml.org/)

2025-07-11 08:09 UTC, mkuehbach commented on docs/references/references.md
> +10. <a name="lxml"></a>[lxml](https://lxml.de/)
10. <a name="lxml - XML and HTML with Python Behnel et al."></a>[lxml - XML and HTML with Python Behnel et al.](https://lxml.de/)

2025-07-11 08:09 UTC, mkuehbach commented on mkdocs.yml
> +  The documentation for the NYAML tool which is a converter tool to transcode NeXus schema from YAML to XML (.nxdl.xml).
Eventually also here XML to YAML and vice-versa

2025-07-11 08:10 UTC, mkuehbach commented on mkdocs.yml
> +  logo: assets/nomad-plugin-logo.png
Agree, see suggestions made for the favicon and nomad-plugin-logo changes abovementioned

2025-07-11 08:13 UTC, mkuehbach commented on docs/learn/workflow.md
> +Presented below is a concise and trimmed example of the `NXmpes` application definition (for discussion purpose) in `YAML` format, alongside its corresponding encoding into `XML` format, as illustrat
The point about that NXmpes is picked here which is mentioned later that it is only an example should be pulled up here already

2025-07-11 08:18 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +## Design of NeXus Ontology and Terms in YAML
do not mention Ontology here, the text explains something different

2025-07-11 08:19 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
"the application definition or the base class schema"

2025-07-11 08:21 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
This covers the `category`, `type`, `doc`, and `symbols` blocks and the name of the schema (e.g. `NXmpes(NXobject)`).

"blocks" or "parameters" unsure about this

2025-07-11 08:21 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
Not immediately but ideal would be to make our punctuation consistent
https://superior-english.com/2017/08/08/comma-after-i-e-and-e-g/

2025-07-11 08:23 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
"(and XML attribute)" > "(an XML attribute)"

2025-07-11 08:24 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
"paranthesis" > "parenthesis"

2025-07-11 08:25 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
make a full-stop before "an application definition may extend"

2025-07-11 08:28 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +[NeXus groups](https://manual.nexusformat.org/design.html#design-groups), as instances of NeXus base classes, embody the compositional structure of application definitions. Depending on the value of
as instances of NeXus base classes, and instances of the NXDL/XSD groupType,

2025-07-11 08:29 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +[NeXus groups](https://manual.nexusformat.org/design.html#design-groups), as instances of NeXus base classes, embody the compositional structure of application definitions. Depending on the value of
"can hold three district values: `specified`, `any`, and `partial`" > "can hold one of three distinct values: `specified`, `any`, or `partial`"

2025-07-11 08:31 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +    <group name="source_TYPE" type="NXsource" recommended="true">
add XML attribute nameType="partial"

2025-07-11 08:32 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +A NeXus `group` may contain NeXus `fields`, NeXus `attributes`, and other NeXus `groups`. A `field`, which is written as a string without a preceding `NX`, and an `attribute`, preceded by `\@`, must
A `field` representing an instance of NXDL/XSD fieldType,

2025-07-11 08:34 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +A NeXus `group` may contain NeXus `fields`, NeXus `attributes`, and other NeXus `groups`. A `field`, which is written as a string without a preceding `NX`, and an `attribute`, preceded by `\@`, must
"has an implicit type `NX_CHAR` by default

2025-07-11 08:36 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +The NeXus `link` reduces data duplication since several concepts of the same kind (e.g., NeXus `group`, `field`, or `attribute`) can refer to a single copy of a data element. In YAML format, NeXus `l
"In YAML format, NeXus `link` is defined denoting the link inside parenthesis." > needs editing

2025-07-11 08:36 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +<!-- ### NeXus Choice
We should at least mention that we do not consistently support this

2025-07-11 17:29 UTC, mkuehbach requested changes
See comments

2025-07-12 14:25 UTC, mkuehbach commented on DeleteDownloaded_nyaml_Paper/paper.pdf
These two files should be removed

2025-07-12 14:25 UTC, mkuehbach commented on DeleteDownloaded_nyaml_Paper/paper.zip
Remove

2025-07-12 14:31 UTC, mkuehbach commented on docs/learn/workflow.md
> +The `nyaml` implements a specific workflow for converting between YAML and XML formats. The `nyaml` converter checks for the correct file type and calls the appropriate converter. For an XML file, th
"the application definitions or base classes" use singular from like for XML direction aforementioned

2025-07-12 14:43 UTC, mkuehbach commented on docs/learn/workflow.md
> +After the conversion from `XML` format to `YAML` format, the `nyaml` tool stores the `XML` contents at the end of the file under a hash created by Secure Hash Algorithm sha256 from `YAML` contents ge
Rather a comment:

We should at least in one place though mention that this hashing is also used because of the fact that the round trip conversions do not contain order otherwise even if the tool were implemented more rigorously, the xsd tells clearly that complex types are sequences meaning the order of the XML attributes and concepts matters. For a normal set of concepts it does not. https://www.balisage.net/Proceedings/vol26/html/LaFontaine01/BalisageVol26-LaFontaine01.html and https://stackoverflow.com/questions/14917943/python-lxml-enforcing-a-specific-order-for-attributes where doing neither and caching is a practical workaround

https://lxml.de/FAQ.html
https://github.com/nexusformat/definitions/blob/8237a9c2c417d4d3d25f72c9e5e69a6707fca337/nxdl.xsd#L986

2025-07-12 14:44 UTC, mkuehbach commented on docs/learn/workflow.md
> +          source_TYPE(NXsource):
nameType should be added even though this being an old example

2025-07-12 14:47 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +In the YAML schema certain keywords hold self significance beyond their literal interpretations. These special keywords are utilized to elucidate and denote various NeXus terms like `attributes`, `fi
Certain keywords hold significance beyond ... to elucidate ...

This improves clarity and specificity

2025-07-12 14:49 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +To initialize a NeXus `group`, `field` or `attribute` the keyword `nameType` carries very significant information on the initialized name depending whether all characters are upper case, lower case o
Invert order "To initialize ... `attribute` and "the keyword `nameType`

i.e. reformulate like this
"The keyword `nameType` carries significant information for defining the name of instances. The following table shows .."

2025-07-12 14:50 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +The `exists` keyword plays a pivotal role in defining the optionality of NeXus concepts `attribute`, `field`, `link`, and `group`. It provides crucial insights for the expected presence or absence of
The keyword `exists`, use parallel structures, i.e. the same way of writing the paragraphs to assist users

2025-07-12 14:52 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +The `exists` keyword plays a pivotal role in defining the optionality of NeXus concepts `attribute`, `field`, `link`, and `group`. It provides crucial insights for the expected presence or absence of
pivotal and crucial using important and only once suffices, see https://www.science.org/doi/10.1126/sciadv.adt3813

2025-07-12 14:54 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +In the above example, the `detector_voltage` field is defined as a `NX_FLOAT` type with a unit of `NX_VOLTAGE`, indicating that the values stored in this field are measured in volts or millivolts or
Do not point that it is NX_FLOAT in this paragraph important is the unit type only

2025-07-12 14:56 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +The `dimensions` term  describes the multidimensional nature of the data, specifying its rank, dimensional indices, and corresponding length of the rank. The attribute `rank` defines the dimension of
rank = "the number of physical dimensions"

2025-07-12 14:57 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +The `dimensions` term  describes the multidimensional nature of the data, specifying its rank, dimensional indices, and corresponding length of the rank. The attribute `rank` defines the dimension of
"that each array" 

add "which"  

"corresponds to a keyword"

2025-07-12 15:00 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +List of strings which are considered as a set of predefined values for fields or attributes. Individual items of the enumeration may also hold a `doc` keyword to provide a description of the item.
for `field` and attribute` hyphenation like in the other paragraphs that explain keywords for the sake of consistency

2025-07-12 15:01 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +`open_enum` says along with the listed items other items are also valid while initializing the NeXus object.
The parameter `open_enum` defines that also other items are valid

2025-07-12 15:04 UTC, mkuehbach requested changes
completes feedback from @mkuehbach

2025-07-14 08:14 UTC, RubelMozumder commented on docs/index.md
> +- [Workflow of the nyaml tool with examples](learn/workflow.md)
addressed!

2025-07-14 08:14 UTC, RubelMozumder commented on docs/learn/workflow.md
> +Presented below is a concise and trimmed example of the `NXmpes` application definition (for discussion purpose) in `YAML` format, alongside its corresponding encoding into `XML` format, as illustrat
Inlcuded in note!

2025-07-14 08:28 UTC, RubelMozumder commented on mkdocs.yml
> +  - Reference: references/references.md
Addressed!

2025-07-14 08:32 UTC, RubelMozumder commented on mkdocs.yml
> +  - pymdownx.emoji: # TODO make sure this isn't used!!
addressed!

2025-07-14 08:32 UTC, RubelMozumder commented on mkdocs.yml
> +  logo: assets/nomad-plugin-logo.png
New logos are added!

2025-07-14 08:32 UTC, RubelMozumder commented on mkdocs.yml
> +  The documentation for the NYAML tool which is a converter tool to transcode NeXus schema from YAML to XML (.nxdl.xml).
addressed!

2025-07-14 08:36 UTC, RubelMozumder commented on docs/howtos/howto.md
> +# nyaml Installation and Command
Addressed!

2025-07-14 08:37 UTC, RubelMozumder commented on docs/howtos/howto.md
> +## How to Install nyaml
Addressed!

2025-07-14 08:37 UTC, RubelMozumder commented on docs/howtos/howto.md
> +## How to Use the nyaml Tool
addressed!

2025-07-14 08:44 UTC, RubelMozumder commented on docs/howtos/howto.md
> +The `--output-file` option defines the output file name (including the fle extension), otherwise the converter will define the output file name from the input file, e.g., for a input file `NXapplicat
This are option flags.

2025-07-14 08:50 UTC, RubelMozumder commented on docs/howtos/howto.md
> +The `--output-file` option defines the output file name (including the fle extension), otherwise the converter will define the output file name from the input file, e.g., for a input file `NXapplicat
Addressed!

2025-07-14 08:54 UTC, RubelMozumder commented on docs/learn/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
Addressed!

2025-07-14 09:02 UTC, RubelMozumder commented on docs/learn/explanations.md
> +At the NeXus data format's core, the NeXus Definition Language (NXDL) functions as the cornerstone through which scientists delineate the nomenclature and organizational structure of information with
addressed!

2025-07-14 09:05 UTC, RubelMozumder commented on docs/learn/explanations.md
> +To expedite the schema development process, we have introduced the use of Yet Another Markup Language ([YAML](https://yaml.org/)), which provides a syntax or style specifically tailored for defining
Addressed!

2025-07-14 09:06 UTC, RubelMozumder commented on docs/learn/explanations.md
> +While `YAML` offers a more readable and concise way to author NeXus definitions, a transcoding mechanism is required because the official format remains XML. The [nyaml](https://github.com/FAIRmat-NF
Addressed!

2025-07-14 09:12 UTC, RubelMozumder commented on docs/learn/workflow.md
> +The `nyaml` implements a specific workflow for converting between YAML and XML formats. The `nyaml` converter checks for the correct file type and calls the appropriate converter. For an XML file, th
Addressed!

2025-07-14 09:14 UTC, RubelMozumder commented on docs/learn/workflow.md
> +After the conversion from `XML` format to `YAML` format, the `nyaml` tool stores the `XML` contents at the end of the file under a hash created by Secure Hash Algorithm sha256 from `YAML` contents ge
Text for workflow explanation reviewed and updated!

2025-07-14 09:15 UTC, RubelMozumder commented on docs/learn/workflow.md
> +    The `NXmpes` application is an old and trimmed version which does not serve any scientific purpose, but only is used to illustrate the results of the conversion process.
Updated!

2025-07-14 09:15 UTC, RubelMozumder commented on docs/references/references.md
> +#References
Addressed!

2025-07-14 09:16 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +## Design of NeXus Ontology and Terms in YAML
Addressed!

2025-07-14 09:17 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +[NeXus groups](https://manual.nexusformat.org/design.html#design-groups), as instances of NeXus base classes, embody the compositional structure of application definitions. Depending on the value of
Addressed!

2025-07-14 09:17 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +[NeXus groups](https://manual.nexusformat.org/design.html#design-groups), as instances of NeXus base classes, embody the compositional structure of application definitions. Depending on the value of
Addressed!

2025-07-14 09:21 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +    <group name="source_TYPE" type="NXsource" recommended="true">
Addressed!

2025-07-14 09:28 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +The NeXus `link` reduces data duplication since several concepts of the same kind (e.g., NeXus `group`, `field`, or `attribute`) can refer to a single copy of a data element. In YAML format, NeXus `l
addressed!

2025-07-14 09:31 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +In the YAML schema certain keywords hold self significance beyond their literal interpretations. These special keywords are utilized to elucidate and denote various NeXus terms like `attributes`, `fi
Addressed!

2025-07-14 10:00 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +The `dimensions` term  describes the multidimensional nature of the data, specifying its rank, dimensional indices, and corresponding length of the rank. The attribute `rank` defines the dimension of
Improved!

2025-07-14 10:05 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +`open_enum` says along with the listed items other items are also valid while initializing the NeXus object.
Addressed!

2025-07-14 10:06 UTC, RubelMozumder commented on docs/index.md
> +# FAIRmat nyaml documentation
Addressed!

2025-07-14 10:11 UTC, RubelMozumder commented on docs/index.md
> +The `nyaml` tool offers a user-friendly command-line interface for converting between `YAML` and `XML` representations of NeXus definitions written in the NeXus Definition Language (NXDL). While the
Addressed!

2025-07-14 10:12 UTC, RubelMozumder commented on docs/index.md
> +The tool supports both application definitions and base classes. It can be installed via `pip` and includes comprehensive documentation and tutorials to assist users in writing NeXus definitions usin
improved!

2025-07-15 08:23 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +In the above example, the `detector_voltage` field is defined as a `NX_FLOAT` type with a unit of `NX_VOLTAGE`, indicating that the values stored in this field are measured in volts or millivolts or
I really not see any problem mentioning type `NX_FLOAT`, but the overall paragraph is mainly focused on the `units`.

2025-07-15 08:27 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +To initialize a NeXus `group`, `field` or `attribute` the keyword `nameType` carries very significant information on the initialized name depending whether all characters are upper case, lower case o
reformulated!

2025-07-15 08:39 UTC, RubelMozumder commented on docs/learn/workflow.md
> +          source_TYPE(NXsource):
Added!

2025-07-15 08:40 UTC, RubelMozumder commented on pyproject.toml
> +    # Mkdocs and the related plugins
addressed!

2025-07-15 08:40 UTC, RubelMozumder commented on src/nyaml/comment_collector.py
> +class YAMLComment(Comment):  # noqa: PLW1641
Addressed!

2025-07-15 08:40 UTC, RubelMozumder commented on README.md
> +Check full documentation of the tool in [gh] https://fairmat-nfdi.github.io/nyaml/
Addressed!

2025-07-15 08:41 UTC, RubelMozumder commented on docs/learn/workflow.md
> +    For indetailed explanation with examples please follow the [Tutorials for writing NeXus definition in YAML](../tutorials/tutorials.md).
Refactored the description of the workflow.

2025-07-15 08:42 UTC, RubelMozumder commented on docs/learn/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
Addressed!

2025-07-15 08:45 UTC, RubelMozumder commented on docs/assets/nomad-plugin-logo.png
Removed!

2025-07-15 08:47 UTC, RubelMozumder commented on docs/howtos/howto.md
> +`nyaml` works as a command line tool to convert NeXus application definitions or base classes from `yaml` file format into the `nxdl.xml` file format and vice-versa. The converter can be called by th
addressed!

2025-07-15 08:54 UTC, RubelMozumder commented on docs/howtos/howto.md
> +The `--output-file` option defines the output file name (including the fle extension), otherwise the converter will define the output file name from the input file, e.g., for a input file `NXapplicat
addressed!

2025-07-15 08:54 UTC, RubelMozumder commented on docs/howtos/howto.md
> +The `--output-file` option defines the output file name (including the fle extension), otherwise the converter will define the output file name from the input file, e.g., for a input file `NXapplicat
Addressed!

2025-07-15 09:01 UTC, RubelMozumder commented on docs/learn/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
I'm not sure why the `NeXus-FAIRmat` is outdated. The platform where the appdef and base classes are being represented from `nexus-definition` repo.

2025-07-15 09:02 UTC, RubelMozumder commented on docs/references/references.md
> +2. <a name="NeXus-FAIRmat proposal"></a>[NeXus-FAIRmat proposal](https://fairmat-experimental.github.io/nexus-fairmat-proposal/)
See previous comment!

2025-07-15 09:06 UTC, RubelMozumder commented on docs/assets/.gitignore
> +nomad-oasis*.zip
removed!

2025-07-15 09:06 UTC, RubelMozumder commented on docs/references/references.md
> +5. <a name="Könnecke, M. et al."></a>[Könnecke, M. et al.](https://doi.org/10.1107/S1600576714027575)
addressed!

2025-07-15 09:21 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +A NeXus `group` may contain NeXus `fields`, NeXus `attributes`, and other NeXus `groups`. A `field`, which is written as a string without a preceding `NX`, and an `attribute`, preceded by `\@`, must
addressed!

2025-07-15 09:24 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +<!-- ### NeXus Choice
addressed!

2025-07-15 09:32 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +The `exists` keyword plays a pivotal role in defining the optionality of NeXus concepts `attribute`, `field`, `link`, and `group`. It provides crucial insights for the expected presence or absence of
Yeah, `exists` is a keyword like other keywords and nothing special for attributes, fields, and groups.

2025-07-15 09:35 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
Addressed!

2025-07-15 09:35 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
Addressed!

2025-07-15 09:41 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +Within the YAML format, the root section denotes the top-level description of the application definition or base class schema, comprising the `category`, `type`, `doc`, `symbols` block, and the name
Addresed!

2025-07-15 09:45 UTC, RubelMozumder commented on docs/tutorials/tutorials.md
> +List of strings which are considered as a set of predefined values for fields or attributes. Individual items of the enumeration may also hold a `doc` keyword to provide a description of the item.
`enumeration` is a keyword like other keywords; nothing differs for NeXus `field` `attribute`. I think it's fine current explanations.

2025-07-15 11:45 UTC, lukaspie commented on docs/howtos/howto.md
> +with the available options:
We don't need this anymore because we get it automatically from mkdocs-click. Please remove.

2025-07-15 11:45 UTC, lukaspie commented on docs/howtos/howto.md
> +`--output-file`: The option defines the output file name (including the file extension), if the option is not specified the converter will define the output file name from the input file. Exemplified
Why not make this a list?

2025-07-15 11:45 UTC, lukaspie commented on docs/learn/explanations.md
> +To expedite the schema development process, recently, we have introduced the use of Yet Another Markup Language ([YAML](https://yaml.org/)), which provides a syntax or style specifically tailored for
It isn't called Yet Another Markup Language anymore, maybe just use the acronym
```suggestion
To expedite the schema development process, recently, we have introduced the use of [YAML](https://yaml.org/), which provides a syntax or style specifically tailored for defining scientific domain-driven schemas with NXDL. One significant advantage of YAML over XML is its indentation-driven approach, which eliminates the need for starting and ending tags for each entity within the schema. Thus, the use of YAML format reduces repetition of NXDL keywords and offers a more intuitive structure aligned with object-oriented programming concepts, such as class inheritance. These benefits are attained without compromising the integrity of the original NeXus schema, which is traditionally expressed in XML format.
```

2025-07-15 11:45 UTC, lukaspie commented on docs/learn/explanations.md
> +While `YAML` offers a more readable and concise way to author NeXus definitions, a transcoding mechanism is required because the official format remains XML. The [nyaml](https://github.com/FAIRmat-NF
Decide if you want to write plain "YAML" or "`YAML`"

2025-07-15 12:05 UTC, mkuehbach commented on docs/learn/explanations.md
> +While `YAML` offers a more readable and concise way to author NeXus definitions, a transcoding mechanism is required because the official format remains XML. The [nyaml](https://github.com/FAIRmat-NF
This is a point about consistent writing, trivial fix:
1.) Make a choice e.g. `YAML`
2.) Search for occurrences and replace by above-choice
3.) Leave a comment like fixed and done

2025-07-15 12:06 UTC, mkuehbach commented on docs/learn/explanations.md
> +To expedite the schema development process, recently, we have introduced the use of Yet Another Markup Language ([YAML](https://yaml.org/)), which provides a syntax or style specifically tailored for
Trivial thing, fixed? if so, mention and resolve

2025-07-15 12:08 UTC, mkuehbach commented on docs/howtos/howto.md
> +`--output-file`: The option defines the output file name (including the file extension), if the option is not specified the converter will define the output file name from the input file. Exemplified
Leaving the ```--help`` environment as is okay as well.
Followed by one blank line and one paragraph for each option, i.e.
Line 45 indent by one line

2025-07-15 12:09 UTC, mkuehbach commented on docs/howtos/howto.md
> +with the available options:
Trivial thing, was it removed, please feedback and resolve, thank you

2025-07-15 12:10 UTC, mkuehbach commented on docs/learn/explanations.md
Was this addressed?

2025-07-15 12:11 UTC, mkuehbach commented on docs/learn/explanations.md
> +The NeXus data format, described by the NeXus Definition Language (NXDL), represents a concerted effort aimed at facilitating data exchange within scientific communities, particularly among those eng
Irrelevant why they are outdated, they are, please update the link to as you said the https://fairmat-nfdi.github.io/nexus_definitions/, comment and resolve

2025-07-15 12:14 UTC, mkuehbach commented on docs/tutorials/tutorials.md
> +The `exists` keyword plays a pivotal role in defining the optionality of NeXus concepts `attribute`, `field`, `link`, and `group`. It provides crucial insights for the expected presence or absence of
The point was to remove excess words

2025-07-15 12:15 UTC, mkuehbach commented on docs/references/references.md
> +2. <a name="NeXus-FAIRmat proposal"></a>[NeXus-FAIRmat proposal](https://fairmat-experimental.github.io/nexus-fairmat-proposal/)
https://fairmat-nfdi.github.io/nexus_definitions/ is to be used

2025-07-15 15:05 UTC, RubelMozumder commented on docs/howtos/howto.md
> +with the available options:
modified. Yeah, mkdocs-click brings the list of options with command line descriptions. But these are not sufficient added small interpretation fot those options.

2025-07-15 15:06 UTC, RubelMozumder commented on docs/learn/explanations.md
> +While `YAML` offers a more readable and concise way to author NeXus definitions, a transcoding mechanism is required because the official format remains XML. The [nyaml](https://github.com/FAIRmat-NF
Kept `YAML` and fixed the inconsistency over the md files.

2025-07-15 15:06 UTC, RubelMozumder commented on docs/howtos/howto.md
> +`--output-file`: The option defines the output file name (including the file extension), if the option is not specified the converter will define the output file name from the input file. Exemplified
included!

2025-07-16 06:43 UTC, RubelMozumder commented on .github/workflows/build_docs.yml
> +    branches: [MyDoc]
Revert it to `main`

2025-07-16 06:48 UTC, RubelMozumder commented on docs/learn/explanations.md
Addressed!

2025-07-16 07:15 UTC, lukaspie approved these changes
lgtm

2025-07-16 07:16 UTC, mkuehbach approved these changes
a reasonable set of changes

2025-07-16 14:14 UTC, merged