src layout.
FAIRmat-NFDI/nyaml pull request #39
Opened 2024-09-16 13:11 UTC by RubelMozumder

2024-09-16 15:12 UTC, mkuehbach requested changes
functionally, lgtm but recommendation to check CI for all python version 3.8 - 3.12

2024-09-16 15:12 UTC, mkuehbach commented on .github/workflows/pylint.yaml
Recommend to use the newer github actions from our pynxtools-PLUGINS to test for all python version automatically

2024-09-16 15:55 UTC, RubelMozumder commented
@mkuehbach this should be fine now.

2024-09-17 09:29 UTC, lukaspie approved these changes
```
[tool.ruff]
include = ["nyaml/*.py", "tests/*.py"]
```
should be changed to
```
[tool.ruff]
include = ["src/nyaml/*.py", "tests/*.py"]
```

Other than that, LGTM.

2024-09-17 14:27 UTC, merged